name = "latih-proxy"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "latih-db"
database_id = "bc44be7f-b667-4fa8-828a-6d3c2c86745e"

[[kv_namespaces]]
binding = "KV_MEDIA"
id = "f964900ad8df4799a088370a6fb8d5f3"

